name: Testing Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  vitest:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: skilaverkefni-2

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Vitest
        run: npm run test -- --run

  cypress:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: skilaverkefni-2

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: skilaverkefni-2
          start: npm run dev
          wait-on: "http://localhost:5173"
          browser: chrome